server:
  port: 8081
# 配置 kafka
spring:
  kafka:
    # 服务器
    bootstrap-servers: 127.0.0.1:9092
    # 配置生产者
    producer:
      # 序列化方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息重发
      retries: 0
      buffer-memory: 33554432
      batch-size: 16384
      acks: -1
    # 配置消费者
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: topic_first
      # 是否开发自动提交
      enable-auto-commit: false
      auto-commit-interval: 1000
      auto-offset-reset: latest

