# 数据脱敏配置,未成功。
server:
  port: 8081
  servlet:
    context-path: /Sharding
# 引入 数据库的相关配置
spring:
  main:
    # 配置，一个实体类对应多张表，覆盖
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      # 指定数据源名称  一个是 springboot_1,springboot_2  一个是  school_1
      names: master,slave
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot_1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
        username: root
        password: Zkong_1234
        type: com.alibaba.druid.pool.DruidDataSource
      slave:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/springboot_1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
        username: root
        password: Zkong_1234
        type: com.alibaba.druid.pool.DruidDataSource
    # 配置规则
    masterslave:
      # 读写分离配置 ，轮询
      load-balance-algorithm-type: round_robin
      # 最终的数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称
      slave-data-source-names: slave
    # 配置脱敏
    # 配置 sql 语句输出
    props:
      sql:
        show: true
      query:
        with:
          cipher:
            # 是否使用密文列查询
            column: true
    encrypt:
      # 类型
      encryptors:
        encryptor_aes:
          # 配置加密的类型
          type: aes
          props:
            # 配置加密的值
            aes.key.value: 123456
      # 配置表脱敏方式
      tables:
        encry:
          columns:
            # 加密列配置
            ps_origin:
              logicColumn: ps
              plainColumn: ps_encry
              cipherColumn: ps_origin
              # 与  spring.shardingsphere.encrypt.encryptors.encryptor_aes 对应
              encryptor: encryptor_aes

#整合mybatis时使用的
mybatis-plus:
  # 配置 mapper文件的位置
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  # 配置日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #  配置别名设置
  global-config:
    db-config:
      logic-delete-field: flag   # 逻辑删除的字段
      logic-not-delete-value: 1  # 正常状态下，该字段的值
      logic-delete-value: 0      # 删除后，该字段的值
      table-underline: true # 驼峰方式转换
#分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
