server:
  port: 8081
  servlet:
    context-path: /MongoDB
# 配置 MongoDB 数据库
spring:
  data:
    mongodb:
      host: 192.168.100.117
      database: zk_monitor
      username: zkong
      password: Zkong_1234
      port: 27017
      # 配置空闲时最小连接数
      minConnectionsPerHost: 20
      # 最大连接数
      connectionsPerHost: 1024
      # 允许阻塞等待连接的线程数量的倍数
      threadsAllowedToBlockForConnectionMultiplier: 5


